# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
  - cd rasterWidget
  
install:
 - ./travis-tool.sh github_package jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'