install.packages("htmlwidgets")
install.packages("devtools")
install.packages("raster")
install.packages("classInt")
install.packages("rgdal")
install.packages("roxygen2")

use_travis('/Users/christopherstephan/Documents/git/rasterWidget/rasterWidget')
devtools::document()
devtools::use_build_ignore("rasterWidget.Rproj", escape = TRUE, pkg = "/Users/christopherstephan/Documents/git/rasterWidget/rasterWidget")
