# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - cd cd /home/travis/build/ChristopherStephan/rasterWidget/rasterWidget
